version: '3'

services:
  geoserver:
    image: kartoza/geoserver
    ports:
      - "8080:8080"
    volumes:
      - ~/geoserver_data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=mypassword
    restart: unless-stopped